# Welcome to Serverless!
#
#
# For full config options, check the docs:
#    docs.serverless.com

service: qos-fixtures

provider:
  name: aws
  runtime: nodejs6.10
  profile: serverless

functions:
  scrape:
    handler: handler.scrape
    memorySize: 256
    events:
      - http:
          path: calendar/qos.ical
          method: get

